---
title: "clustering"
author: "Sean Wei"
date: "11/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggrepel)

knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE, warning = FALSE}
prescription_data <- readRDS("prescription_data.rds")
overdose_data <- readRDS("all_overdoses.rds")

# for example filter by 2018
full_data <- left_join(prescription_data, overdose_data, by = c("year", "State")) %>% 
  select(State, year, prescription_rate, Age.Adjusted.Rate) %>% 
  janitor::clean_names() %>% 
  filter(year == 2017) %>% 
  mutate_if(is.numeric, funs(`std`=scale(.) %>% as.vector())) %>% 
  select(-c(year_std))

silhouette_score <- function(k){
  km <- kmeans(full_data[,5:6], centers = k, nstart = 20)
  score <- cluster::silhouette(km$cluster, dist(full_data[, 2:3]))
  mean(score[, 3])
}

k <- 2:10
avg_sil <- sapply(k, silhouette_score)
avg_sil
optimal_k <- which(as.data.frame(avg_sil)$avg_sil == max(avg_sil)) + 1

km <- kmeans(full_data[, 5:6], centers = optimal_k, nstart = 20)

full_data <- mutate(full_data, cluster = as.character(km$cluster))

ggplot(data = full_data, aes(x = prescription_rate_std, y = age_adjusted_rate_std)) + 
  geom_point(aes(color = cluster)) +
  geom_text_repel(aes(label = state, color = cluster), size = 3) +
  geom_point(data = as.data.frame(km$centers)
             , aes(x = prescription_rate_std, y = age_adjusted_rate_std)
             , pch = "X"
             , size = 3) +
  labs(x = "Average Prescription Rate", y = "Average Age Adjusted Overdose Rate", color = "Cluster Assignment")
```

```{r}
library(maps)

usa_states <- map_data(map = "state", region = ".") %>% 
  mutate(state = stringr::str_to_title(region))

cluster_map <- full_data %>%
  inner_join(usa_states, by = "state")

ggplot(cluster_map, aes(x = long, y = lat, group = group, fill = cluster)) +
      geom_polygon(color = "white") +
      theme_void() +
      coord_fixed(ratio = 1.3) +
      labs(title = "Opioid Prescription Rate by State",
           subtitle = "MME Prescribed per 100 People",
           fill = "") +
      theme(legend.position="right")
```




