---
title: "prescription_wrangle"
author: "Tamer Sullivan"
date: "11/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(tidyr)
library(tidyverse)
library(dplyr)

```

```{r}
#upload csv files

#2006
raw_data_2006 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2006_CDC_state_prescription_data.csv") %>% 
  rename(`2006` = `2006 Prescribing Rate`)

#2007
raw_data_2007 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2007_CDC_state_prescription_data.csv") %>% 
  rename(`2007` = `2007 Prescribing Rate`)

#2008
raw_data_2008 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2008_CDC_state_prescription_data.csv") %>% 
  rename(`2008` = `2008 Prescribing Rate`)

#2009
raw_data_2009 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2009_CDC_state_prescription_data.csv") %>% 
  rename(`2009` = `2009 Prescribing Rate`)

#2010
raw_data_2010 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2010_CDC_state_prescription_data.csv") %>% 
  rename(`2010` = `2010 Prescribing Rate`)

#2011
raw_data_2011 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2011_CDC_state_prescription_data.csv") %>% 
  rename(`2011` = `2011 Prescribing Rate`)

#2012
raw_data_2012 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2012_CDC_state_prescription_data.csv") %>% 
  rename(`2012` = `2012 Prescribing Rate`)

#2013
raw_data_2013 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2013_CDC_state_prescription_data.csv") %>% 
  rename(`2013` = `2013 Prescribing Rate`)

#2014
raw_data_2014 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2014_CDC_state_prescription_data.csv") %>% 
  rename(`2014` = `2014 Prescribing Rate`)

#2015
raw_data_2015 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2015_CDC_state_prescription_data.csv") %>% 
  rename(`2015` = `2015 Prescribing Rate`)

#2016
raw_data_2016 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2016_CDC_state_prescription_data.csv") %>% 
  rename(`2016` = `2016 Prescribing Rate`)

#2017
raw_data_2017 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2017_CDC_state_prescription_data.csv") %>% 
  rename(`2017` = `2017 Prescribing Rate`)

#2018
raw_data_2018 <- readr::read_csv("//Users/tamersullivan/Documents/School/Fall 2020 classes/Data Science/Blog-Pill-Posse/blog-data-raw/2018_CDC_state_prescription_data.csv") %>% 
  rename(`2018` = `2018 Prescribing Rate`)

#PIVOT EACH TABLE TO GET YEAR AS VALUE

prescription_2006 <- raw_data_2006 %>%
  pivot_longer(`2006`, names_to = "year")

prescription_2007 <- raw_data_2007 %>%
  pivot_longer(`2007`, names_to = "year")

prescription_2008 <- raw_data_2008 %>%
  pivot_longer(`2008`, names_to = "year")

prescription_2009 <- raw_data_2009 %>%
  pivot_longer(`2009`, names_to = "year")

prescription_2010 <- raw_data_2010 %>%
  pivot_longer(`2010`, names_to = "year")

prescription_2011 <- raw_data_2011 %>%
  pivot_longer(`2011`, names_to = "year")

prescription_2011 <- raw_data_2011 %>%
  pivot_longer(`2011`, names_to = "year")

prescription_2012 <- raw_data_2012 %>%
  pivot_longer(`2012`, names_to = "year")

prescription_2013 <- raw_data_2013 %>%
  pivot_longer(`2013`, names_to = "year")

prescription_2014 <- raw_data_2014 %>%
  pivot_longer(`2014`, names_to = "year")

prescription_2015 <- raw_data_2015 %>%
  pivot_longer(`2015`, names_to = "year")

prescription_2016 <- raw_data_2016 %>%
  pivot_longer(`2016`, names_to = "year")

prescription_2017 <- raw_data_2017 %>%
  pivot_longer(`2017`, names_to = "year") %>%
  rename("State ABBR" = Abbreviation)

prescription_2018 <- raw_data_2018 %>%
  pivot_longer(`2018`, names_to = "year") %>%
  rename("State ABBR" = Abbreviation)


#STACK TABLES ON TOP OF EACH OTHER

all_prescription_data <- rbind(prescription_2006, prescription_2007, 
                               prescription_2008, prescription_2009, 
                               prescription_2010, prescription_2011, 
                               prescription_2012, prescription_2013, 
                               prescription_2014, prescription_2015, 
                               prescription_2016, prescription_2017, 
                               prescription_2018) %>% 
  filter(year >= 2014) %>% 
  mutate(year = as.integer(year)) %>% 
  filter(`State ABBR` != "DC") %>% 
  filter(`State ABBR` != "US")

saveRDS(all_prescription_data, file = "prescription_data.rds")


```


```{r}
# Overdose Data
overdose_2014 <- read.csv("//Users/cmurphy/git/Blog-Pill-Posse/blog-data-raw/Overdose Deaths - 2014 Overdose.csv")
overdose_2015 <- read.csv("//Users/cmurphy/git/Blog-Pill-Posse/blog-data-raw/Overdose Deaths - 2015 Overdose.csv")
overdose_2016 <- read.csv("//Users/cmurphy/git/Blog-Pill-Posse/blog-data-raw/Overdose Deaths - 2016 Overdose.csv")
overdose_2017 <- read.csv("//Users/cmurphy/git/Blog-Pill-Posse/blog-data-raw/Overdose Deaths - 2017 Overdose.csv")
overdose_2018 <- read.csv("//Users/cmurphy/git/Blog-Pill-Posse/blog-data-raw/Overdose Deaths - 2018 Overdose.csv")

all_overdoses<- rbind(overdose_2014,overdose_2015,overdose_2016,overdose_2017,overdose_2018)

all_overdoses <- all_overdoses %>% 
  rename(year = Year) %>% 
  arrange(year) %>%
  filter(State != "Washington D.C.")

saveRDS(all_overdoses, file = "all_overdoses.rds")
```